version: '2'
services:
  wordpress:
    image: wordpress
    ports:
      - 8082:80
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=wp_db
    links:
      - wordpress_db:wp_db

  wordpress_db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3307:3306
    volumes:
      - /doc/wordpress_db:/var/lib/mysql